name: Daily Pokemon TCG Sync
on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:      # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Fetch Pokemon TCG data
        run: node scripts/fetch-cards.js
        
      - name: Fetch pricing data
        run: node scripts/fetch-pricing.js
        
      - name: Merge and optimize data
        run: node scripts/merge-data.js
        
      - name: Upload to Shopify
        run: node scripts/upload-shopify.js
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          
      - name: Commit updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update Pokemon TCG data $(date)" || exit 0
          git push
